// Code generated by "stringer -type=Type,DamageCategory"; DO NOT EDIT.

package pokemon

import "strconv"

const _Type_name = "NormalFightingFlyingPoisonGroundRockBugGhostSteelFireWaterGrassElectricPsychicIceDragonDarkFairyBird"

var _Type_index = [...]uint8{0, 6, 14, 20, 26, 32, 36, 39, 44, 49, 53, 58, 63, 71, 78, 81, 87, 91, 96, 100}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}

const _DamageCategory_name = "PhysicalSpecialStatus"

var _DamageCategory_index = [...]uint8{0, 8, 15, 21}

func (i DamageCategory) String() string {
	if i < 0 || i >= DamageCategory(len(_DamageCategory_index)-1) {
		return "DamageCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DamageCategory_name[_DamageCategory_index[i]:_DamageCategory_index[i+1]]
}
